### ISSUE TITLE
bugzillarest must use api token for auth

### ISSUE THREAD

**Issue by acs** [grimoirelab/perceval#111]
The current implementation in the bugzillarest for login:

https://bugzilla.mozilla.org/rest/login?login=user_login&password=XXXXXXX

does not work anymore.

requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://bugzilla.mozilla.org/rest/login?login=user_login&password=XXXXXXX

The backend shall use api tokens.

**Comment by sduenas** [comment]
Bugzilla REST backend makes use of api tokens since de beginning. Instead of passing user and password, just set the token with `-t, --api-token` arguments.

In any case, I've checked the output of the login URL with a browser and the output returned by the server is:

```
{
   "code" : 32000,
   "documentation" : "http://www.bugzilla.org/docs/tip/en/html/api/",
   "error" : true,
   "message" : "API key authentication is required."
}
```

We have to mange this error better to let the users know that they need to use the api-token instead of the user/password parameters.
