### ISSUE TITLE
Can MBox python module fetch mailboxes?

### ISSUE THREAD

**Issue by heatherbooker** [grimoirelab/perceval#136]
I'm wondering if using the MBox module in python (as seen in example at bottom of page [here](https://jgbarah.gitbooks.io/grimoirelab-training/perceval/mail.html) is capable of fetching remote resources, or does it ignore the uri it is given? Since the comment in the example says "you need to have the archives to analyzed there[in dirpath] before running the script", but if that's the case, why does it require a uri?

Thanks!

**Comment by sduenas** [comment]
The URI is used to set the origin of the data you get from that MBox.

Each item generated by Perceval has an origin (you can find it at the top level of each item as `origin`). It is also used to generate a unique identifier for each item (field `uuid`).

As an URI can be an address to a HTTP resource, or to a FTP, or a link on the filesystem, or any other thing, we decided MBox backend will only get local messages. The responsibility of accessing remote resources/repositories is out of scope for this backend. That's why there are other backends such as `pipermail`, the defunct `gmane` or `hypperkitty` that do part of this job. These backends use MBox behind the curtain, though.
