### ISSUE TITLE
Supported URLs for bugzilla

### ISSUE THREAD

**Issue by iganchevup8** [grimoirelab/perceval#96]
Please consider this as a question/feature request.

Of what I understand with using the bugzilla backend, it looks for an URL of the style: https://bugzilla.organization.org/. It doesn't support URL schema as the following: https://bugzilla.organization.org/buglist.cgi?product=project. Is my understanding correct?

If this is the case, it would be nice to support also the mentioned URL schema. Often one may need only the Bugzilla of a single project (say gedit) and not the bug repository for the entire organization (gnome in this case). IIRC in bicho there was the possibility to ask only for a single project, so it is a pity it's not the case in perceval.

Would it be complicated to implement this?

**Comment by sduenas** [comment]
Well, this is a topic that comes from time to time in the internal development of Perceval backends: whether support or not different filters than `--from-date` or `--offset` for each backend. We consider that a filter is a thing like _product_ or _module_ in Bugzilla, or a _page_ in Mediawiki and so on.

In my opinion, we should support them soon but I still don't know how soon. It has the benefits you commented before but it has some problems and drawbacks we need to solve/have clear first before going on this.

For instance, in the case of Bugzilla, bugs can be moved from a project to another. You can end up with bugs, which you fetched at some point in time but that aren't anymore on that project, and you don't notice that their status changed because you aren't tracking that project. You can avoid this problem fetching again all the bugs from that project (without using `--from-date`) but in some cases you can't because you want the activity of a project updated in hours or minutes.

The persistent cache/backup support is another problem. It isn't the best cache in the world but it is nice and if you use it wisely, you can skip some hours fetching data that you downloaded before. If we add filters, we need to define how to store data in the cache using those filters and how to restore them.

I also would like to track how the items were fetched. Now it is easy, the metadata fields `origin` and `timestamp` allow us to do it but if we use filters, should we put the list of filters in the metadata fields too?

These are some of the problems but there are are others and that's why I'm so reticent to include filters now without having think twice these.

BTW, I lied a little and there are some backends that already have filters. Those are `stackexchange`, `meetup` and `github` but just because it's (almost) impossible to fetch all the data stored on their systems.
